name: arcas-hla
channels:
- bioconda
- conda-forge
dependencies:
- bedtools==2.31.1
- biopython==1.84
- coreutils==9.4
- git==2.47.0
- git-lfs==3.5.1
- kallisto==0.44.0
- numpy==2.1.0
- pandas==2.2.3
- pigz==2.8
- pip==24.3.1
- pyarrow==17.0.0
- pytest==8.3.4
- python==3.13.0
- samtools==1.21
- scipy==1.14.1
